apiVersion: v1
# Тип
kind: Service
metadata:
  # Имя сервиса
  name: django-service
spec:
  type: NodePort
  # Имя селектора (labels из пода)
  selector:
    app.kubernetes.io/name: django
  # Порты
  ports:
      # Протокол (TCP/UDP/SCTP)
    - protocol: TCP
      # Порт СЕРВИСА (внутри кластера
      port: 80
      # Порт ПОДА (куда под отдает)
      targetPort: 80
      # Порт НОДЫ (для доступа снаружи)
      nodePort: 30000